apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-deployment
  labels:
    app: bookmyshow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bookmyshow
        image: naren3005/bookmyshow:latest
        ports:
        - containerPort: 3008
        imagePullPolicy: Always
